server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hogwarts
    username: student
    password: chocolatefrog
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.yml


avatars.dir.path: avatars


